### ISSUE TITLE
5-bus example not functional in MacOS

### ISSUE THREAD

**Issue by jd-lara** [NREL/FESTIV_MODEL#2]
There are a couple of issues with FESTIV in MacOS with Matlab R2018a

Is the 5 -bus example currently functioning? I get the following error

```Matlab
>> which wgdx
/Applications/GAMS30.2/GAMS Terminal.app/Contents/MacOS/wgdx.mexmaci64
>> which FESTIV
/Users/jdlara/Dropbox/Code/FESTIV_MODEL/FESTIV.m
>> FESTIV
***********************************************************************
* Flexible Energy Scheduling Tool for Integrating Variable generation *
***********************************************************************
**   FFFFFF    EEEEEE    SSSSSS    TTTTTTTT    IIIIII    VV     VV   **
**   FF        EE        SS           TT         II       VV   VV    **
**   FFFFFF    EEEEEE    SSSSSS       TT         II        VV VV     **
**   FF        EE            SS       TT         II         VVV      **
**   FF        EEEEEE    SSSSSS       TT       IIIIII        V       **
***********************************************************************
**************** National Renewable  Energy Laboratory ****************
***********************************************************************
 
Warning: For non-Windows platforms the path to gams matlab files are assumed to be in
MATLABPATH 
> In getgamspath (line 31)
  In FESTIV (line 94) 
Input File: PJM_5_BUS
Reading Input Files...Undefined function or variable 'STARTUP_VALUE_STRING3'.

Error in READ_IN_SYSTEM_DATA_FROM_EXCEL (line 670)
STARTUP_VALUE.uels = {STARTUP_VALUE_STRING1' STARTUP_VALUE_STRING3};

Error in FESTIV (line 114)
    READ_IN_SYSTEM_DATA_FROM_EXCEL
```

**Comment by erikgela** [comment]
@jd-lara This was an error EPRI made in modifying the code that should have been part of a Mod for a project. Will revert the code to correct the issue in the next few days.

**Comment by jd-lara** [comment]
bump to @erikgela about this.

**Comment by jd-lara** [comment]
@erikgela I made another test with the current master. This is the output 

```Matlab
>> which wgdx
/Applications/GAMS30.2/GAMS Terminal.app/Contents/MacOS/wgdx.mexmaci64
>> 
>> FESTIV
***********************************************************************
* Flexible Energy Scheduling Tool for Integrating Variable generation *
***********************************************************************
**   FFFFFF    EEEEEE    SSSSSS    TTTTTTTT    IIIIII    VV     VV   **
**   FF        EE        SS           TT         II       VV   VV    **
**   FFFFFF    EEEEEE    SSSSSS       TT         II        VV VV     **
**   FF        EE            SS       TT         II         VVV      **
**   FF        EEEEEE    SSSSSS       TT       IIIIII        V       **
***********************************************************************
**************** National Renewable  Energy Laboratory ****************
***********************************************************************
 
Warning: For non-Windows platforms the path to gams matlab files are assumed to be in
MATLABPATH 
> In getgamspath (line 31)
  In FESTIV (line 94) 
Warning: The value of local variables may have been changed to match the globals.
Future versions of MATLAB will require that you declare a variable to be global before
you use that variable. 
> In READ_IN_SYSTEM_DATA_FROM_EXCEL (line 8)
  In FESTIV (line 114) 
Input File: PJM_5_BUS
Reading Input Files...Complete! (00 min, 02.15 s)
Modeling Initial Day-Ahead Unit Commitment...zsh:1: command not found: gams
Error using rgdx
File 'TEMP/TOTAL_DASCUCOUTPUT.gdx' not found!


Error in getgamsdata (line 18)
GENSET_TMP = rgdx(input1,gen_rgdx);

Error in RUN_DASCUC (line 23)
    =
    getgamsdata('TOTAL_DASCUCOUTPUT','DASCUC','YES',GEN,INTERVAL,BUS,BRANCH,RESERVETYPE,SYSTEMVALUE_VAL,RESERVEVALUE_VAL,GENPARAM,STORAGEVALUE_VAL,BRANCHPARAM);
    
Error in FESTIV (line 209)
        RUN_DASCUC;
```

**Comment by jd-lara** [comment]
@erikgela bump on this issue. Is it possible to get this version of FESTIV to work?

**Comment by erikgela** [comment]
@jd-lara the original error on this issue should have been resolved with the Mar 1 commit. The error you show above looks like you may not have appropriately added gams path to environment variables since it looks like it is not able to run the gams command. You'll have to address this on your own.

**Comment by RehmanZafar26** [comment]
Dear @erikgela, I also having this issue it seems some file is missing.

 Input File: PJM_5_BUS
Reading Input Files...Complete! (01 min, 12.06 s)
Modeling Initial Day-Ahead Unit Commitment...'gams' is not recognized as an internal or external command, 
operable program or batch file. 
Error using rgdx
File 'TEMP\TOTAL_DASCUCOUTPUT.gdx' not found!


Error in getgamsdata (line 18)
GENSET_TMP = rgdx(input1,gen_rgdx);

Error in RUN_DASCUC (line 23)
    =
    getgamsdata('TOTAL_DASCUCOUTPUT','DASCUC','YES',GEN,INTERVAL,BUS,BRANCH,RESERVETYPE,SYSTEMVALUE_VAL,RESERVEVALUE_VAL,GENPARAM,STORAGEVALUE_VAL,BRANCHPARAM);

Error in FESTIV (line 209)
        RUN_DASCUC;

**Comment by ibrahimkrad** [comment]
the TOTAL_XXXOUTPUT.gdx files are generated automatically after the appropriate GAMS model finishes solving. Check the DASCUC.lst and DASCUC.log files to see what happened during the optimization.

**Comment by NasirAbbas514** [comment]
Dear @erikgela, I also having this issue while I have added the gams path to the environmental variables.

Input File: PJM_5_BUS
Reading Input Files...Complete! (01 min, 12.06 s)
Modeling Initial Day-Ahead Unit Commitment...'gams' is not recognized as an internal or external command,
operable program or batch file.
Error using rgdx
File 'TEMP\TOTAL_DASCUCOUTPUT.gdx' not found!

Error in getgamsdata (line 18)
GENSET_TMP = rgdx(input1,gen_rgdx);

Error in RUN_DASCUC (line 23)
=
getgamsdata('TOTAL_DASCUCOUTPUT','DASCUC','YES',GEN,INTERVAL,BUS,BRANCH,RESERVETYPE,SYSTEMVALUE_VAL,RESERVEVALUE_VAL,GENPARAM,STORAGEVALUE_VAL,BRANCHPARAM);

Error in FESTIV (line 209)
RUN_DASCUC;
