### ISSUE TITLE
Output argument "gamspath" (and maybe others) not assigned during call to "getgamspath".

### ISSUE THREAD

**Issue by NasirAbbas514** [NREL/FESTIV_MODEL#3]
Hi

I am trying to run the existing test case in FESTIV as provided here [https://github.com/NREL/FESTIV_MODEL] in point number 2. 

But I am having an error continuously. I will add the screenshot for that. As the error is about GAMS, I tried it doing multiple times after reinstalling GAMS again and again and then adding the GAMS path to MATLAB and windows environment variables as well but all in vain.

![Screenshot (53)](https://user-images.githubusercontent.com/76805743/132301053-92ec0a4c-6769-4e09-836c-d68af760632c.png)

**Comment by pikr001** [comment]
That's strange. Did you try to put a breakpoint in that file to see why it's having a hard time determining the GAMS path? This script is meant to discover the path to your gams.exe file. Is there something different about your directory/installation?

**Comment by NasirAbbas514** [comment]
I have installed gams from this link **[https://www.gams.com/download/**]
Have I downloaded the right gams for this? I am confused now because I tried searching the gams.exe file but there is no file with such a name in the gams directory.  I am adding different screenshots related to this so that you can understand my problem easily,

and i tried running the festiv.m file with a pause on errors and it still shows the error only on line 94 of the festiv.m file. 
![Screenshot (64)](https://user-images.githubusercontent.com/76805743/132456667-48763d76-5e14-4d70-ba20-494ff64d0260.png)
![Screenshot (65)](https://user-images.githubusercontent.com/76805743/132456671-73b0f89b-e74c-4dbb-bb84-210ba6f20abe.png)

**Comment by NasirAbbas514** [comment]
![Screenshot (66)](https://user-images.githubusercontent.com/76805743/132458278-f8157254-f44c-4f94-a29b-ceedc83c4d9b.png)

**Comment by NasirAbbas514** [comment]
I solved this issue by updating the oathfile.txt, but now I am having a different issue and that is
Dear @erikgela, I also having this issue it seems some file is missing.

Input File: PJM_5_BUS
Reading Input Files...Complete! (01 min, 12.06 s)
Modeling Initial Day-Ahead Unit Commitment...'gams' is not recognized as an internal or external command,
operable program or batch file.
Error using rgdx
File 'TEMP\TOTAL_DASCUCOUTPUT.gdx' not found!

Error in getgamsdata (line 18)
GENSET_TMP = rgdx(input1,gen_rgdx);

Error in RUN_DASCUC (line 23)
=
getgamsdata('TOTAL_DASCUCOUTPUT','DASCUC','YES',GEN,INTERVAL,BUS,BRANCH,RESERVETYPE,SYSTEMVALUE_VAL,RESERVEVALUE_VAL,GENPARAM,STORAGEVALUE_VAL,BRANCHPARAM);

Error in FESTIV (line 209)
RUN_DASCUC;

**Comment by pikr001** [comment]
GAMS is not being called ('gams' is not recognized...) so the gdx file is never being created. Try to hardcode your gamspath on line 94 (gamspath='C:\path\to\gams'). that should force MATLAB to find it.

**Comment by NasirAbbas514** [comment]
I commented the line 94 and did what you advised     
     %gamspath=getgamspath();
        gamspath='C:\GAMS\36';
but still it is not working and i am having the same errors while running the festiv.m file

**Comment by pikr001** [comment]
From your screenshots, looks like you are using version 33, did you confirm the directory for the installation?

**Comment by NasirAbbas514** [comment]
I am using GAMS 36 version and yes the directory of installation is confirmed. and that is
C:\GAMS\36
![Screenshot (69)](https://user-images.githubusercontent.com/76805743/132635316-48472b77-9630-4567-a760-4824679d2433.png)
